### ISSUE TITLE
LDAP  group sync error

### ISSUE THREAD

**Issue by Ovalgee** [Lama3L9R/ArtifactoryKeygen#6]
[65051aeb628353cc] [.s.s.a.l.LdapSearchService:151] [27.0.0.1-8040-exec-8] - Search Ldap groups only supported for Pro license

**Comment by Lama3L9R** [comment]
As I mentioned in another issue, not all components in Artifactory are using the same License Manager. I will investigate on this later but can you please check if this is leading to any unavailable features? Or its just a random log message that doesn't affect anything

**Comment by Ovalgee** [comment]
Yeah, the LDAP and crowd auth can not work

**Comment by fykin** [comment]
Some code in _LdapSearchService_ is for this problem.
```
    public List<LdapGroup> searchGroups(LdapGroupsSetting groupsSetting, LdapSetting ldapSetting) {
        if (!this.licenseService.isPro()) {
            log.warn("Search Ldap groups only supported for Pro license");
            return Collections.emptyList();
        } else {
            String filter = groupsSetting.getFilter();
            LdapContextSource securityContext = LdapUtils.createSecurityContext(ldapSetting, ((AccessConfiguration)this.configurationServicePool.getInternalConfigurationService().getConfiguration()).getSecurity().getAuthentication().getLdap());
            return this.search(GroupLdapContext.builder().securityContext(securityContext).ldapSetting(ldapSetting).groupsSetting(groupsSetting).build(), filter);
        }
    }
```

**Comment by fykin** [comment]
I found the source of Product.Type::isPro
```
    public static enum Type {
        OSS,
        COMMERCIAL,
        COMMERCIAL_XWE,
        TRIAL,
        TRIAL_XWE,
        ENTERPRISE,
        EDGE_TRIAL,
        EDGE,
        ENTERPRISE_PLUS_TRIAL,
        ENTERPRISE_PLUS;

        private Type() {
        }

        public static Type fromName(String name) {
            return (Type)EnumUtils.fromValue(values(), name, Enum::toString);
        }

        public boolean isTrial() {
            return this == TRIAL || this == ENTERPRISE_PLUS_TRIAL || this == EDGE_TRIAL;
        }

        public boolean isEnterprise() {
            return this.compareTo(ENTERPRISE) >= 0;
        }

        public boolean isEdge() {
            return this == EDGE || this == EDGE_TRIAL;
        }

        public boolean isEnterprisePlus() {
            return this == ENTERPRISE_PLUS || this == ENTERPRISE_PLUS_TRIAL;
        }

        public boolean isPro() {
            return this.compareTo(OSS) > 0;
        }
    }
```

**Comment by fykin** [comment]
Successfully activated LDAP function by using LegacyLicense

**Comment by izumizumov-star** [comment]
How to solve this problem in the end? Where to get a legacy license? How to apply it?

**Comment by fykin** [comment]
> [@fykin](https://github.com/fykin) Can you tell me how to activate the LDAP function using Legacy License?

I wish this can help you.

<img width="1458" height="852" alt="Image" src="https://github.com/user-attachments/assets/5c43aaf9-74a6-42f4-9a48-1aa984d8c3be" />

**Comment by fykin** [comment]
> BTW， how to get the legacy License?
@Ovalgee You can gernerate Legacy License by the libraries which from Artifactory resources.

**Comment by fykin** [comment]
@Ovalgee Some legacy license code for you

<img width="1144" height="629" alt="Image" src="https://github.com/user-attachments/assets/3d43b234-56f4-466f-b27d-d9b7b9911f66" />

**Comment by PatchouliTC** [comment]
> > BTW， how to get the legacy License?
> > [@Ovalgee](https://github.com/Ovalgee) You can gernerate Legacy License by the libraries which from Artifactory resources.

is that mean that artifactory pro instance contain legacylicense lib

**Comment by Shi9mohn** [comment]
> Successfully activated LDAP function by using LegacyLicense

I'd tried legacy license. It works the same: it's possible to connect to LDAP, but impossible to sync groups:

```
[jfac ] [WARN ] [1f4d69d473696211] [l.LegacyLicenseServiceImpl:283] [27.0.0.1-8040-exec-7] - Invalid license. 
org.jfrog.license.exception.LicenseException: License verification failed
        at org.jfrog.license.legacy.SignedLicense.verify(SignedLicense.java:123)
        at org.jfrog.license.legacy.LegacyLicenseManager.load(LegacyLicenseManager.java:93)
        at org.jfrog.license.api.LicenseManager.loadLegacyLicense(LicenseManager.java:260)
        at org.jfrog.license.api.LicenseManager.loadLicense(LicenseManager.java:113)
        at org.jfrog.access.server.service.license.LegacyLicenseServiceImpl.loadLicense(LegacyLicenseServiceImpl.java:281)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1685)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:652)
        at org.jfrog.access.server.service.license.LegacyLicenseServiceImpl.hasAppropriateLicense(LegacyLicenseServiceImpl.java:137)
        at org.jfrog.access.server.service.license.LegacyLicenseServiceImpl.lambda$initCache$5(LegacyLicenseServiceImpl.java:225)
        at com.google.common.base.Suppliers$ExpiringMemoizingSupplier.get(Suppliers.java:261)
        at org.jfrog.access.server.service.license.LegacyLicenseServiceImpl.isPro(LegacyLicenseServiceImpl.java:92)
        at org.jfrog.access.server.service.auth.ldap.LdapSearchService.searchGroups(LdapSearchService.java:101)
        at org.jfrog.access.server.service.auth.ldap.LdapGroupServiceImpl.searchGroups(LdapGroupServiceImpl.java:137)
        at org.jfrog.access.server.rest.resource.ui.ldap.group.UiLdapGroupResource.searchLdapGroups(UiLdapGroupResource.java:127)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
```

@fykin does Legacy License allow to sync LDAP Groups in your case?

**Comment by fykin** [comment]
> > Successfully activated LDAP function by using LegacyLicense
> 
> I'd tried legacy license. It works the same: it's possible to connect to LDAP, but impossible to sync groups:
> 
> ```
> [jfac ] [WARN ] [1f4d69d473696211] [l.LegacyLicenseServiceImpl:283] [27.0.0.1-8040-exec-7] - Invalid license. 
> org.jfrog.license.exception.LicenseException: License verification failed
>         at org.jfrog.license.legacy.SignedLicense.verify(SignedLicense.java:123)
>         at org.jfrog.license.legacy.LegacyLicenseManager.load(LegacyLicenseManager.java:93)
>         at org.jfrog.license.api.LicenseManager.loadLegacyLicense(LicenseManager.java:260)
>         at org.jfrog.license.api.LicenseManager.loadLicense(LicenseManager.java:113)
>         at org.jfrog.access.server.service.license.LegacyLicenseServiceImpl.loadLicense(LegacyLicenseServiceImpl.java:281)
>         at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
>         at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
>         at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
>         at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
>         at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
>         at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1685)
>         at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
>         at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
>         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
>         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
>         at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
>         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
>         at java.base/java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:652)
>         at org.jfrog.access.server.service.license.LegacyLicenseServiceImpl.hasAppropriateLicense(LegacyLicenseServiceImpl.java:137)
>         at org.jfrog.access.server.service.license.LegacyLicenseServiceImpl.lambda$initCache$5(LegacyLicenseServiceImpl.java:225)
>         at com.google.common.base.Suppliers$ExpiringMemoizingSupplier.get(Suppliers.java:261)
>         at org.jfrog.access.server.service.license.LegacyLicenseServiceImpl.isPro(LegacyLicenseServiceImpl.java:92)
>         at org.jfrog.access.server.service.auth.ldap.LdapSearchService.searchGroups(LdapSearchService.java:101)
>         at org.jfrog.access.server.service.auth.ldap.LdapGroupServiceImpl.searchGroups(LdapGroupServiceImpl.java:137)
>         at org.jfrog.access.server.rest.resource.ui.ldap.group.UiLdapGroupResource.searchLdapGroups(UiLdapGroupResource.java:127)
>         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:580)
> ```
> 
> [@fykin](https://github.com/fykin) does Legacy License allow to sync LDAP Groups in your case?

Yes, I do. Did you crack public key in the artifactory?

**Comment by fykin** [comment]
> > > BTW， how to get the legacy License?
> > > [@Ovalgee](https://github.com/Ovalgee) You can gernerate Legacy License by the libraries which from Artifactory resources.
> 
> is that mean that artifactory pro instance contain legacylicense lib

Yes. You need to replace public key in the license class.

**Comment by rooozar** [comment]
Can I get a mini-instruction on how to fix ldap?

**Comment by Shi9mohn** [comment]
> Yes, I do. Did you crack public key in the artifactory?

@fykin I'd injected ArtifactoryAgent with setenv.sh. I'd got private key for encryption using ArtifactoryKeygen. Everything works well, but LDAP Groups shows an error I'd described above.

**Comment by Shi9mohn** [comment]
@fykin I'd checked Artifactory 7.104.6 (version from readme) - the same issue.

```
[jfac ] [WARN ] [028e4cf01d1ca04b] [l.LegacyLicenseServiceImpl:283] [27.0.0.1-8040-exec-7] - Invalid license. 
org.jfrog.license.exception.LicenseException: License verification failed
        at org.jfrog.license.legacy.SignedLicense.verify(SignedLicense.java:123)
        at org.jfrog.license.legacy.LegacyLicenseManager.load(LegacyLicenseManager.java:93)
        at org.jfrog.license.api.LicenseManager.loadLegacyLicense(LicenseManager.java:260)
        at org.jfrog.license.api.LicenseManager.loadLicense(LicenseManager.java:113)
        at org.jfrog.access.server.service.license.LegacyLicenseServiceImpl.loadLicense(LegacyLicenseServiceImpl.java:281)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1685)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:652)
        at org.jfrog.access.server.service.license.LegacyLicenseServiceImpl.hasAppropriateLicense(LegacyLicenseServiceImpl.java:137)
        at org.jfrog.access.server.service.license.LegacyLicenseServiceImpl.lambda$initCache$5(LegacyLicenseServiceImpl.java:225)
        at com.google.common.base.Suppliers$ExpiringMemoizingSupplier.get(Suppliers.java:261)
        at org.jfrog.access.server.service.license.LegacyLicenseServiceImpl.isPro(LegacyLicenseServiceImpl.java:92)
        at org.jfrog.access.server.service.auth.ldap.LdapSearchService.searchGroups(LdapSearchService.java:119)
        at org.jfrog.access.server.service.auth.ldap.LdapGroupServiceImpl.searchGroups(LdapGroupServiceImpl.java:126)
        at org.jfrog.access.server.rest.resource.ui.ldap.group.UiLdapGroupResource.searchLdapGroups(UiLdapGroupResource.java:127)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
...
```

**Comment by Shi9mohn** [comment]
@fykin with Enterprise Plus license I have another error:

```
[jfac ] [WARN ] [04a1277f7276ab8c] [l.LegacyLicenseServiceImpl:283] [27.0.0.1-8040-exec-3] - Invalid license. 
org.jfrog.license.exception.LicenseException: Failed to decrypt license: last block incomplete in decryption
        at org.jfrog.license.legacy.LegacyLicenseManager.decrypt(LegacyLicenseManager.java:145)
        at org.jfrog.license.legacy.LegacyLicenseManager.load(LegacyLicenseManager.java:89)
        at org.jfrog.license.api.LicenseManager.loadLegacyLicense(LicenseManager.java:260)
        at org.jfrog.license.api.LicenseManager.loadLicense(LicenseManager.java:113)
        at org.jfrog.access.server.service.license.LegacyLicenseServiceImpl.loadLicense(LegacyLicenseServiceImpl.java:281)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1685)
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:652)
        at org.jfrog.access.server.service.license.LegacyLicenseServiceImpl.hasAppropriateLicense(LegacyLicenseServiceImpl.java:137)
        at org.jfrog.access.server.service.license.LegacyLicenseServiceImpl.lambda$initCache$5(LegacyLicenseServiceImpl.java:225)
```

**Comment by fykin** [comment]
@Shi9mohn @rooozar 
This code is only for generating lagacy license key. You also need to crack the license librarys and inject the public into its. The path of the libraries are app/artifactory/tomcat/webapps/artifactory/WEB-INF/lib/artifactory-addons-manager-xxx.jar and  ./app/access/tomcat/webapps/access/WEB-INF/lib/license-manager-xxxx.jar.

<img width="1144" height="629" alt="Image" src="https://github.com/user-attachments/assets/f687fc92-4109-48fd-a99a-767f2388b9a5" />

**Comment by fykin** [comment]
> [@fykin](https://github.com/fykin) I'd checked Artifactory 7.104.6 (version from readme) - the same issue.
> 
> ```
> [jfac ] [WARN ] [028e4cf01d1ca04b] [l.LegacyLicenseServiceImpl:283] [27.0.0.1-8040-exec-7] - Invalid license. 
> org.jfrog.license.exception.LicenseException: License verification failed
>         at org.jfrog.license.legacy.SignedLicense.verify(SignedLicense.java:123)
>         at org.jfrog.license.legacy.LegacyLicenseManager.load(LegacyLicenseManager.java:93)
>         at org.jfrog.license.api.LicenseManager.loadLegacyLicense(LicenseManager.java:260)
>         at org.jfrog.license.api.LicenseManager.loadLicense(LicenseManager.java:113)
>         at org.jfrog.access.server.service.license.LegacyLicenseServiceImpl.loadLicense(LegacyLicenseServiceImpl.java:281)
>         at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
>         at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
>         at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
>         at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
>         at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
>         at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1685)
>         at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
>         at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
>         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
>         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
>         at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
>         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
>         at java.base/java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:652)
>         at org.jfrog.access.server.service.license.LegacyLicenseServiceImpl.hasAppropriateLicense(LegacyLicenseServiceImpl.java:137)
>         at org.jfrog.access.server.service.license.LegacyLicenseServiceImpl.lambda$initCache$5(LegacyLicenseServiceImpl.java:225)
>         at com.google.common.base.Suppliers$ExpiringMemoizingSupplier.get(Suppliers.java:261)
>         at org.jfrog.access.server.service.license.LegacyLicenseServiceImpl.isPro(LegacyLicenseServiceImpl.java:92)
>         at org.jfrog.access.server.service.auth.ldap.LdapSearchService.searchGroups(LdapSearchService.java:119)
>         at org.jfrog.access.server.service.auth.ldap.LdapGroupServiceImpl.searchGroups(LdapGroupServiceImpl.java:126)
>         at org.jfrog.access.server.rest.resource.ui.ldap.group.UiLdapGroupResource.searchLdapGroups(UiLdapGroupResource.java:127)
>         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:580)
> ...
> ```

The key step is lost. You should inject your own public key to the license manager library.

**Comment by fykin** [comment]
1. app/artifactory/tomcat/webapps/artifactory/WEB-INF/lib/artifactory-addons-manager-xxx.jar

<img width="2530" height="708" alt="Image" src="https://github.com/user-attachments/assets/c31b8448-ae59-4a44-9054-040365524369" />

<img width="3380" height="696" alt="Image" src="https://github.com/user-attachments/assets/3c7979a8-651c-4da8-9c28-f495cec8653d" />

2. app/access/tomcat/webapps/access/WEB-INF/lib/license-manager-xxxx.jar

<img width="3162" height="772" alt="Image" src="https://github.com/user-attachments/assets/f5ff3e24-2eb5-4f07-a048-f8d149ad0071" />

<img width="3138" height="752" alt="Image" src="https://github.com/user-attachments/assets/a94ac328-c48d-4614-9932-44213b64d53d" />

Compiling and compressing, and replacing the origin libraries.

**Comment by fykin** [comment]
@rooozar @Shi9mohn You can use artifactory-pro-7.111.9

**Comment by nimah79** [comment]
Check out my patch repo. It works on the latest version of JFrog Artifactory (7.133.15):

https://github.com/nimah79/jfrog-artifactory-license-patcher

**Comment by Ovalgee** [comment]
Good job for some guys that not familiar the java code, Thanks! @nimah79
